# Funciones aleatorias

Hablando de funciones no podemos olvidar las funciones aleatorias encontradas en el módulo `random`. [En la documentación oficial](https://numpy.org/doc/stable/reference/random/index.html) encontraréis el listado completo con ejemplos de uso.

Tenemos funciones para generar arrays con `datos aleatorios` y `permutaciones`. También hay muchas enfocadas a generar muestras de distribuciones de probabilidad pensadas para visualizar estadística.

Vamos a practicar algunas de las dos primeras.

## Datos aleatorios

In [1]:
import numpy as np

In [2]:
# número decimal entre 0 y 1
np.random.rand()

0.5232177902613518

In [3]:
# array 1D de decimales entre 0 y 1
np.random.rand(4)

array([0.9657102 , 0.07821398, 0.58759399, 0.74597642])

In [4]:
# array 2D de decimales entre 0 y 1
np.random.rand(4,2)

array([[0.87171222, 0.28925076],
       [0.90756118, 0.47772272],
       [0.19497565, 0.63114586],
       [0.18063542, 0.9189318 ]])

In [5]:
# array 3D de decimales entre 0 y N
np.random.uniform(10, size=[2,2,2])

array([[[2.64884118, 1.662668  ],
        [1.86334145, 7.41656249]],

       [[3.89534702, 1.3374108 ],
        [9.68230024, 3.55550117]]])

In [6]:
# array 4D de decimales entre -N y M
np.random.uniform(-10, 10, size=[2,2,2,2])

array([[[[ 3.20388292, -7.36722747],
         [ 9.63572525,  9.63954016]],

        [[-4.69651103, -3.17956331],
         [-3.73213312,  5.04478726]]],


       [[[ 9.35305036,  8.94146816],
         [ 8.14456348,  2.41919828]],

        [[-5.30971772, -3.67226398],
         [ 8.8503147 ,  1.65920916]]]])

In [7]:
# número entero entre 0 y N
np.random.randint(10)

2

In [8]:
# array de enteros entre 0 y N
np.random.randint(10, size=[3,2])

array([[7, 9],
       [0, 4],
       [6, 6]])

In [9]:
# array de enteros entre -N y M
np.random.randint(-10, 10, size=[3,2])

array([[ -3,   3],
       [  6,  -1],
       [ -1, -10]])

In [10]:
# array uniforme con curva gaussiana
np.random.normal(size=20)

array([-1.38621872, -1.04249539,  1.6921478 ,  1.07113301, -0.43183152,
        0.01627874,  0.97724162, -0.30279625,  0.98411126, -0.6549778 ,
        0.07562158,  1.54799914, -1.22433794, -1.84411129, -2.70810269,
        0.46733658,  0.50683487,  0.04948681, -1.11926575,  1.61081848])

## Permutaciones

In [11]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# desordenar un array
np.random.shuffle(arr)

arr

array([3, 6, 5, 1, 0, 4, 2, 9, 8, 7])

In [13]:
# generar secuencia permutada a partir de un número
np.random.permutation(15)

array([ 5,  2,  6, 12,  9, 10, 11,  3,  4,  7, 14, 13,  8,  0,  1])