# Filtrado de arrays

En esta lección vamos a repasar algunas funciones para filtrar arrays. Para más información sobre las funciones disponibles no olvidéis pasaros por [la documentación oficial](https://numpy.org/doc/stable/reference/index.html).

## Filtro unique

Devuelve un array de una dimensión borrando todos los elementos duplicados:

In [1]:
import numpy as np

In [2]:
# generamos un array con números aleatorios repetidos
arr = np.random.randint(0, 10, 40)

In [3]:
arr

array([4, 4, 0, 1, 9, 8, 4, 7, 2, 4, 2, 0, 5, 1, 6, 0, 4, 5, 7, 5, 6, 6,
       8, 7, 5, 4, 5, 1, 2, 4, 0, 3, 8, 8, 3, 5, 0, 0, 9, 7])

In [4]:
# aplicamos el filtro unique
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Filtro in1d

Devuelve un array de una dimensión indicando si los elementos de una lista se encuentran en otro array:

In [5]:
np.in1d([-1, 4, 8, 12], arr)

array([False,  True,  True, False])

## Filtro where

Sirve para generar un array filtrado a partir de una condición y un valor por defecto:

In [6]:
# generamos un array con números aleatorios
arr_1 = np.random.uniform(-5, 5, size=[3,2])

arr_1

array([[-4.75546581,  4.57143254],
       [ 0.36289939,  2.85814251],
       [ 2.44734089, -4.44542578]])

In [7]:
# creamos un filtro que establece los negativos a 0
arr_2 = np.where(arr_1<0, 0, arr_1)

arr_2

array([[0.        , 4.57143254],
       [0.36289939, 2.85814251],
       [2.44734089, 0.        ]])

In [8]:
# añadimos otro filtro que establece los positivos a 1
arr_2 = np.where(arr_2>0, True, arr_2)

arr_2

array([[0., 1.],
       [1., 1.],
       [1., 0.]])

## Filtros booleanos

Permiten hacer comprobaciones lógicas en los arrays de booleanos:

In [9]:
# definimos un array de booleanos
arr_bool = np.array([True,True,True,False])

In [10]:
# comprobar si todos los elementos del array son True
arr_bool.all()

False

In [11]:
# comprobar si al menos un elementos del array es True
arr_bool.any()

True

También funciona con múltiples dimensiones pasando el eje:

In [12]:
# definimos un array de booleanos 2d
arr_bool_2d = np.array(
    [
        [False, True],
        [False, True],
        [False, True]
    ]
)

arr_bool_2d

array([[False,  True],
       [False,  True],
       [False,  True]])

In [13]:
# comprobar si alguna de las columnas es todo True
arr_bool_2d.all(0)

array([False,  True])

In [14]:
# comprobar si alguna de las filas tiene algún True
arr_bool_2d.any(1)

array([ True,  True,  True])